# POST /chat — conversational endpoint consumed by the Angular client-app.
#
# Request body:
#   - message: str       — the user's natural-language prompt
#   - thread_id: str     — UUID generated by the client per session,
#                          used as the LangGraph checkpoint key to maintain
#                          conversation history across turns
#
# Response:
#   - StreamingResponse with Content-Type: text/event-stream (SSE)
#   - Emits "token" events as Claude streams its answer
#   - Emits a final "done" event when the agent has finished
#
# Flow:
#   1. Retrieve the compiled graph from app state (set during lifespan)
#   2. Build a HumanMessage from the request body
#   3. Call graph.astream_events() with the thread_id as the config key
#   4. Forward streamed tokens to the SSE response
